---
- hosts: webserver
  vars:
    http_port: 80
    max_clients: 200
  remote_user: vagrant
  become: yes
  tasks:

  - name: "install nginx"
    yum:
      name: ['nginx']
      state: latest

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

